apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-db
  name: roar-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roar-db
  template:
    metadata:
      labels:
        app: roar-db
    spec:
      containers:
      - name: roar-db
        image: roar-db
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin

