apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-web
  name: roar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roar-web
  template:
    metadata:
      labels:
        app: roar-web
    spec:
      containers:
      - name: roar-web
        image: roar-web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web

