apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-web
  name: roar-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: roar-web
    spec:
      containers:
      - image: image: roar-web

        imagePullPolicy: Always
        name: roar-web
        ports:
        - containerPort: 8080
          name: web
